### PR TITLE
Test HautelookAliceBundle with Faker Provider

### PR DESCRIPTION
**Pull request by alexislefebvre**

### CODE REVIEW

**Comment by alexisLefebvre** [comment]
The error is:

> 1) Liip\FunctionalTestBundle\Tests\Test\WebTestCaseTest::testLoadFixturesFilesWithHautelook
> InvalidArgumentException: Unknown formatter "foo"

It occurs with Symfony 2.8 and hautelook/alice-bundle v1.2.0.

**Comment by estahn** [comment]
@alexislefebvre Sorry for the late response. Just had a look. The current test is setting up the container service manually. So the container definition set by symfony with your configuration is overwritten.

If you want to have your changes take affect delete the mocked service definition (line 351-355):
https://github.com/alexislefebvre/LiipFunctionalTestBundle/blob/71512250b95a05e2da2651f35f8cd9dad15161f1/Tests/Test/WebTestCaseTest.php#L351

**Comment by alexisLefebvre** [comment]
@estahn thanks a lot, I should have paid attention to the beginning of the test, I didn't see it was defining another provider, sorry. It should work now, I'll clean it and submit a PR to the upstream.

**Comment by alexisLefebvre** [comment]
It has been moved to upstream:

```
https://github.com/liip/LiipFunctionalTestBundle/pull/246
https://github.com/liip/LiipFunctionalTestBundle/pull/247
```

**Pull request closed without merging**
